// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ActionResult/Schema/EntitiesCreatedActionResultDef.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mumble.FirstGame.Serialization.Protobuf.ActionResult {

  /// <summary>Holder for reflection information generated from ActionResult/Schema/EntitiesCreatedActionResultDef.proto</summary>
  public static partial class EntitiesCreatedActionResultDefReflection {

    #region Descriptor
    /// <summary>File descriptor for ActionResult/Schema/EntitiesCreatedActionResultDef.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntitiesCreatedActionResultDefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhBY3Rpb25SZXN1bHQvU2NoZW1hL0VudGl0aWVzQ3JlYXRlZEFjdGlvblJl",
            "c3VsdERlZi5wcm90bxIMYWN0aW9ucmVzdWx0Gh1BY3Rpb24vU2NoZW1hL0Rp",
            "cmVjdGlvbi5wcm90byK9AgoeRW50aXRpZXNDcmVhdGVkQWN0aW9uUmVzdWx0",
            "RGVmEkUKCGVudGl0aWVzGAEgAygLMjMuYWN0aW9ucmVzdWx0LkVudGl0aWVz",
            "Q3JlYXRlZEFjdGlvblJlc3VsdERlZi5FbnRpdHka0wEKBkVudGl0eRIKCgJp",
            "ZBgBIAEoBRJMCgR0eXBlGAIgASgOMj4uYWN0aW9ucmVzdWx0LkVudGl0aWVz",
            "Q3JlYXRlZEFjdGlvblJlc3VsdERlZi5FbnRpdHkuRW50aXR5VHlwZRIJCgF4",
            "GAMgASgCEgkKAXkYBCABKAISJAoJZGlyZWN0aW9uGAUgASgLMhEuYWN0aW9u",
            "LkRpcmVjdGlvbiIzCgpFbnRpdHlUeXBlEgoKBlBsYXllchAAEgkKBUVuZW15",
            "EAESDgoKUHJvamVjdGlsZRACQjeqAjRNdW1ibGUuRmlyc3RHYW1lLlNlcmlh",
            "bGl6YXRpb24uUHJvdG9idWYuQWN0aW9uUmVzdWx0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mumble.FirstGame.Serialization.Protobuf.Action.DirectionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef), global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Parser, new[]{ "Entities" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity), global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Parser, new[]{ "Id", "Type", "X", "Y", "Direction" }, null, new[]{ typeof(global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType) }, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EntitiesCreatedActionResultDef : pb::IMessage<EntitiesCreatedActionResultDef> {
    private static readonly pb::MessageParser<EntitiesCreatedActionResultDef> _parser = new pb::MessageParser<EntitiesCreatedActionResultDef>(() => new EntitiesCreatedActionResultDef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntitiesCreatedActionResultDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDefReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntitiesCreatedActionResultDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntitiesCreatedActionResultDef(EntitiesCreatedActionResultDef other) : this() {
      entities_ = other.entities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntitiesCreatedActionResultDef Clone() {
      return new EntitiesCreatedActionResultDef(this);
    }

    /// <summary>Field number for the "entities" field.</summary>
    public const int EntitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity> _repeated_entities_codec
        = pb::FieldCodec.ForMessage(10, global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Parser);
    private readonly pbc::RepeatedField<global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity> entities_ = new pbc::RepeatedField<global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity> Entities {
      get { return entities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntitiesCreatedActionResultDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntitiesCreatedActionResultDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entities_.Equals(other.entities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      entities_.WriteTo(output, _repeated_entities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += entities_.CalculateSize(_repeated_entities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntitiesCreatedActionResultDef other) {
      if (other == null) {
        return;
      }
      entities_.Add(other.entities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entities_.AddEntriesFrom(input, _repeated_entities_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the EntitiesCreatedActionResultDef message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Entity : pb::IMessage<Entity> {
        private static readonly pb::MessageParser<Entity> _parser = new pb::MessageParser<Entity>(() => new Entity());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Entity> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Entity() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Entity(Entity other) : this() {
          id_ = other.id_;
          type_ = other.type_;
          x_ = other.x_;
          y_ = other.y_;
          direction_ = other.direction_ != null ? other.direction_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Entity Clone() {
          return new Entity(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private int id_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Id {
          get { return id_; }
          set {
            id_ = value;
          }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 2;
        private global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType type_ = global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType.Player;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "x" field.</summary>
        public const int XFieldNumber = 3;
        private float x_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public float X {
          get { return x_; }
          set {
            x_ = value;
          }
        }

        /// <summary>Field number for the "y" field.</summary>
        public const int YFieldNumber = 4;
        private float y_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public float Y {
          get { return y_; }
          set {
            y_ = value;
          }
        }

        /// <summary>Field number for the "direction" field.</summary>
        public const int DirectionFieldNumber = 5;
        private global::Mumble.FirstGame.Serialization.Protobuf.Action.Direction direction_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Mumble.FirstGame.Serialization.Protobuf.Action.Direction Direction {
          get { return direction_; }
          set {
            direction_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Entity);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Entity other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if (Type != other.Type) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
          if (!object.Equals(Direction, other.Direction)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Id != 0) hash ^= Id.GetHashCode();
          if (Type != global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType.Player) hash ^= Type.GetHashCode();
          if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
          if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
          if (direction_ != null) hash ^= Direction.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Id != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Id);
          }
          if (Type != global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType.Player) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          if (X != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(X);
          }
          if (Y != 0F) {
            output.WriteRawTag(37);
            output.WriteFloat(Y);
          }
          if (direction_ != null) {
            output.WriteRawTag(42);
            output.WriteMessage(Direction);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Id != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
          }
          if (Type != global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType.Player) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (X != 0F) {
            size += 1 + 4;
          }
          if (Y != 0F) {
            size += 1 + 4;
          }
          if (direction_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Direction);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Entity other) {
          if (other == null) {
            return;
          }
          if (other.Id != 0) {
            Id = other.Id;
          }
          if (other.Type != global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType.Player) {
            Type = other.Type;
          }
          if (other.X != 0F) {
            X = other.X;
          }
          if (other.Y != 0F) {
            Y = other.Y;
          }
          if (other.direction_ != null) {
            if (direction_ == null) {
              Direction = new global::Mumble.FirstGame.Serialization.Protobuf.Action.Direction();
            }
            Direction.MergeFrom(other.Direction);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Id = input.ReadInt32();
                break;
              }
              case 16: {
                Type = (global::Mumble.FirstGame.Serialization.Protobuf.ActionResult.EntitiesCreatedActionResultDef.Types.Entity.Types.EntityType) input.ReadEnum();
                break;
              }
              case 29: {
                X = input.ReadFloat();
                break;
              }
              case 37: {
                Y = input.ReadFloat();
                break;
              }
              case 42: {
                if (direction_ == null) {
                  Direction = new global::Mumble.FirstGame.Serialization.Protobuf.Action.Direction();
                }
                input.ReadMessage(Direction);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Entity message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          public enum EntityType {
            [pbr::OriginalName("Player")] Player = 0,
            [pbr::OriginalName("Enemy")] Enemy = 1,
            [pbr::OriginalName("Projectile")] Projectile = 2,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
